name: Docker Build Latest

on:
  push:
    branches:
      - main

jobs:
  vm-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            teamveganat/member-dashboard:latest
          build-args: |
            REACT_APP_API_URL=${{ secrets.PROD_REACT_APP_API_URL }}
            REACT_APP_API_KEY=${{ secrets.PROD_REACT_APP_API_KEY }}